//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 PowerMon.rc 使用
//
#define IDD_OPTIONS_DIALOG              102
#define IDS_PLUGIN_NAME                 103
#define IDS_PLUGIN_DESCRIPTION          104
#define IDS_PLUGIN_ITEM_NAME            105
#define IDS_BATTERY_POWER_DISPLAY_LABEL 106
#define IDS_BATTERY_CAPACITY_DISPLAY_LABEL 107
#define IDS_DISCRIPTIVE_BATERY_POWER_HEADER 108
#define IDS_DISCRIPTIVE_BATERY_CAPACITY_HEADER 109
#define IDS_RELOADING_BATTERY_DRIVER_TIP 110
#define IDS_BATTERY_DRIVER_HANDLER_CLEANING 111
#define IDS_DISCRIPTIVE_BATERY_Voltage_HEADER 112
#define IDS_DISCRIPTIVE_BATERY_VOLTAGE_HEADER 112
#define IDS_BATTERY_DRIVER_REBUILDING   113
#define IDS_BATTERY_NONEXISTS           114
#define IDS_BATTERY_INFO_UNKNOWN        115
#define IDC_CHECKBOX_DBGMODE            1001
#define IDC_BUTTON_BTRDRIVER            1003
#define IDC_Change_Unit_String          1005
#define IDC_PWR_UNIT_STR_INPUT          1008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
